#!/usr/bin/env python3
"""Give the hand-written case-study pages the shared site chrome. Idempotent: a second run changes nothing.

    python3 tools/add_site_chrome.py                 # every projects/<slug>/index.html except the
                                                     #   generated projects/equity-research export
    python3 tools/add_site_chrome.py --check         # report only; exits non-zero if a page lacks a piece
    python3 tools/add_site_chrome.py projects/fitlog/index.html   # named pages only

Run it after adding a case-study page. Each piece is inserted only when it is missing; the page's
prose and its own styles and scripts are left alone:

  <head>  the theme-color meta, the site icon, the inline no-flash theme script (applies a saved
          light/dark choice before first paint and gates the scroll reveal) and the site.css link,
          all just before the page's case-study.css link
  <body>  a "Skip to content" link as its first child
          <main id="main"> around the content, from header.cs-head up to footer.cs-foot
          <span class="cs-tools" data-theme-slot></span> at the end of nav.cs-top, where site.js
          mounts the search button and the theme toggle
          <script src="../../assets/site.js" defer></script> before </body>

--early puts a blocking site.js in <head> instead of the deferred one, for a page whose own
non-deferred scripts need the site's theme code before they run. No page needs it today: the SOC
and Tucson charts read html[data-theme] (set by the inline head script) and redraw on the
'themechange' event, which site.js dispatches only after the page has loaded.

projects/equity-research is generated by its export and keeps its own look; it is never touched.
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKIP = {"equity-research"}

CSS_LINK = '<link rel="stylesheet" href="../../assets/case-study.css">'
# The same head lines the homepage (index.html) carries; keep them in sync.
THEME_COLOR = '<meta name="theme-color" content="#f5f1e8">'
ICON = ("<link rel=\"icon\" href=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E"
        "%3Crect width='64' height='64' rx='10' fill='%231c1a17'/%3E%3Ctext x='32' y='43' font-family='Georgia,serif' "
        "font-size='29' text-anchor='middle' fill='%23f5f1e8'%3EBM%3C/text%3E%3Crect x='15' y='50' width='34' height='2' "
        "fill='%236f95e0'/%3E%3C/svg%3E\">")
THEME_SCRIPT = ('<script>!function(d){d.classList.add("js");try{var t=localStorage.getItem("bm-theme");'
                'if(t==="light"||t==="dark")d.setAttribute("data-theme",t)}catch(e){}try{if("IntersectionObserver"in window'
                '&&!matchMedia("(prefers-reduced-motion: reduce)").matches)d.classList.add("reveal")}catch(e){}}'
                '(document.documentElement)</script>')
SITE_CSS = '<link rel="stylesheet" href="../../assets/site.css">'
SITE_JS = '<script src="../../assets/site.js" defer></script>'
SITE_JS_EARLY = '<script src="../../assets/site.js"></script>'
SKIP_LINK = '<a class="skip" href="#main">Skip to content</a>'
SLOT = '<span class="cs-tools" data-theme-slot></span>'

# (name, "already there?" test, head line) — inserted in this order before the case-study.css link
HEAD = [
    ("theme-color meta", lambda h: re.search(r'<meta\s+name="theme-color"', h), THEME_COLOR),
    ("icon", lambda h: re.search(r'<link\s+rel="(?:shortcut )?icon"', h), ICON),
    ("theme script", lambda h: "bm-theme" in h, THEME_SCRIPT),
    ("site.css", lambda h: "assets/site.css" in h, SITE_CSS),
]


def patch(html: str, early: bool = False) -> tuple[str, list[str]]:
    """Return the patched page and the names of the pieces that were missing."""
    missing: list[str] = []
    if CSS_LINK not in html:
        raise ValueError("no case-study.css link")
    lines = []
    for name, has, line in HEAD:
        if not has(html):
            missing.append(name)
            lines.append(line)
    if early and "assets/site.js" not in html:
        missing.append("site.js (early)")
        lines.append(SITE_JS_EARLY)
    if lines:
        html = html.replace(CSS_LINK, "\n".join(lines) + "\n" + CSS_LINK, 1)

    if 'class="skip"' not in html:
        missing.append("skip link")
        html, n = re.subn(r"(<body\b[^>]*>)\n?", lambda m: m.group(1) + "\n" + SKIP_LINK + "\n", html, count=1)
        if n != 1:
            raise ValueError("no <body>")

    if not re.search(r"<main\b", html):
        missing.append("<main> landmark")
        html, a = re.subn(r'(\n[ \t]*)(<header class="cs-head")', r'\1<main id="main" tabindex="-1">\1\2', html, count=1)
        html, b = re.subn(r'(\n[ \t]*)(<footer class="cs-foot")', r'\1</main>\1\2', html, count=1)
        if a != 1 or b != 1:
            raise ValueError("no header.cs-head / footer.cs-foot pair to wrap in <main>")

    if "data-theme-slot" not in html:
        missing.append("cs-tools slot")
        html, n = re.subn(r'(<nav class="cs-top">.*?)(</nav>)', lambda m: m.group(1) + SLOT + m.group(2),
                          html, count=1, flags=re.S)
        if n != 1:
            raise ValueError("no nav.cs-top")

    if "assets/site.js" not in html:
        missing.append("site.js")
        html, n = re.subn(r"</body>", SITE_JS + "\n</body>", html, count=1)
        if n != 1:
            raise ValueError("no </body>")
    return html, missing


def pages(args: list[str]) -> list[pathlib.Path]:
    if args:
        out = [pathlib.Path(a).resolve() for a in args]
    else:
        out = sorted(p for p in (ROOT / "projects").glob("*/index.html") if p.parent.name not in SKIP)
    for p in out:
        if p.parent.name in SKIP or "equity-research" in p.parts:
            sys.exit("refusing to touch %s: the equity-research export is generated" % p)
    return out


def main(argv: list[str]) -> int:
    check = "--check" in argv
    early = "--early" in argv
    bad = 0
    for path in pages([a for a in argv if not a.startswith("--")]):
        old = path.read_text(encoding="utf-8")
        new, missing = patch(old, early)
        rel = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
        if check:
            print(("MISSING %s: %s" % (rel, ", ".join(missing))) if missing else "ok %s" % rel)
            bad += bool(missing)
            continue
        if new != old:
            path.write_text(new, encoding="utf-8")
        print(("patched %s (%s)" % (rel, ", ".join(missing))) if new != old else "unchanged %s" % rel)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
